schema_version: '1.0'
environment:
  grid_size:
  - 8
  - 8
  obstacles:
  - - 2
    - 2
  - - 3
    - 4
  - - 3
    - 5
  - - 3
    - 7
  - - 4
    - 3
  - - 6
    - 2
  - - 6
    - 7
  target_locations:
  - - 6
    - 6
  risk_field:
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  initial_exogenous_state: {}
agents:
  initial_poses:
  - - 0
    - 0
  initial_health:
  - 1.0
map_id: map_003
generation:
  collection_seed: 2026
  map_index: 3
