schema_version: '1.0'
environment:
  grid_size:
  - 8
  - 8
  obstacles:
  - - 1
    - 0
  - - 1
    - 1
  - - 1
    - 2
  - - 4
    - 5
  - - 5
    - 0
  - - 5
    - 1
  - - 6
    - 2
  - - 7
    - 2
  target_locations:
  - - 6
    - 6
  risk_field:
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  initial_exogenous_state: {}
agents:
  initial_poses:
  - - 0
    - 0
  initial_health:
  - 1.0
map_id: map_011
generation:
  collection_seed: 2026
  map_index: 11
